# Generated by Django 4.1.7 on 2023-05-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(blank=True, max_length=70, null=True)),
                ('CategoryDescription', models.CharField(blank=True, max_length=200, null=True)),
                ('CategoryImage', models.ImageField(upload_to='CategoryImage')),
            ],
        ),
    ]
