# Generated by Django 4.1.7 on 2023-05-07 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductCategory', models.CharField(blank=True, max_length=100, null=True)),
                ('ProductName', models.CharField(blank=True, max_length=100, null=True)),
                ('ProductPrice', models.IntegerField(blank=True, null=True)),
                ('ProductDescription', models.CharField(blank=True, max_length=200, null=True)),
                ('ProductBrand', models.CharField(blank=True, max_length=100, null=True)),
                ('ProductImage', models.ImageField(upload_to='ProductImage')),
            ],
        ),
    ]
