# Generated by Django 4.1.7 on 2023-05-22 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SigninDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.CharField(blank=True, max_length=100, null=True)),
                ('Image', models.ImageField(upload_to='ProfilePic')),
                ('Password', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
